name: Google unit tests

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: bricsi/google_test
    steps:
      - uses: actions/checkout@v2
      - name: Build google test and run it
        run: cd tests && cmake CMakeLists.txt && make && ./runUnitTests
