name: Push doxygen documents

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-20.04
    container: bricsi/doxygen
    steps:
      - uses: actions/checkout@main

      - run: doxygen doxconf

      - name: Push git subdir as branch
        uses: s0/git-publish-subdir-action@v2.4.0

        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}