name: check units workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
      - run: sudo apt install -y cppcheck
      - run: sudo apt install -y valgrind
      - run: sudo apt install -y gcc g++

      - name: Code analysis
      - run: cppcheck *.cpp --enable=all --output-file=cppcheck_results.txt
      - run: chmod +x check_warning.sh
      - run: ./check_warning.sh
      - run: chmod +x check_error.sh
      - run: ./check_error.sh

      - name: Upload code analysis result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_results
          path: cppcheck_results.txt

      - name: Build
      - run: g++ -Wall *.cpp -o rpg

      - name: Valgrind check
      - run:  valgrind --leak-check=full --error-exitcode=1 ./rpg units/unit1.json units/unit2.json
      
      - name: In-out tests
      - run: chmod +x run_check_units.sh
      - run: ./run_check_units.sh rpg units_output.txt
      - run: diff units_output.txt units_good_outputs.txt